export const ErrorCode = {
	'AUTH-001': 'Token não encontrado',
	'AUTH-002': 'Token não é válido',
	'AUTH-003': 'Token expirado',
	'AUTH-004': 'Usuário não encontrado',
	'AUTH-005': 'Erro desconhecido',
	'SCHEMA-001': 'Campo não informado',
	'SCHEMA-002': 'Campo inválido',
	'SCHEMA-003': 'Campo obrigatório não informado',
	'FIELD-001': 'Campo inválido',
	'FIELD-002': 'Valor incompativel',
	'FIELD-003': 'Valor inválido',
	'DATABASE-001': 'Registro já existênte',
	'DATABASE-002': 'Registro não encontrado',
}
